FROM jboss/keycloak:16.1.1

COPY ./src/keycloak/realm-export.json /opt/jboss/keycloak/realm-export.json

COPY ./src/keycloak/disable-theme-cache.cli /opt/jboss/startup-scripts/disable-theme-cache.cli
COPY ./src/keycloak/theme /opt/jboss/keycloak/themes/taranis-ng
