FROM python:3.13-alpine3.22 AS production-stage

WORKDIR /app/

# install common packages
RUN \
    apk add --no-cache poetry nginx

COPY ./src/web/requirements.txt /app/requirements.txt

# install dependencies
RUN \
    apk add --no-cache --virtual .build-deps build-base \
    make && \
    pip install --no-cache-dir -r /app/requirements.txt


COPY ./src/web/. /app/
RUN mkdir -p /app/archive/logs
# RUN  cd /app && make dependencies

COPY ./src/web/default.conf /etc/nginx/conf.d/default.conf

COPY ./src/web/gunicorn_conf.py /gunicorn_conf.py
COPY ./src/web/start.sh /start.sh
RUN chmod +x /start.sh
COPY ./src/web/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# setup environment variables
ENV PYTHONPATH=/app
ENV MODULE_NAME run
ENV VARIABLE_NAME app
ENV GUNICORN_CMD_ARGS --timeout 120

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/start.sh"]
